theme: jekyll-theme-minimal
title: Seungjun Nah
description: <p><b>Ph. D. candidate</b><br>Department of ECE, SNU, Seoul, Korea</p>
logo: https://avatars1.githubusercontent.com/u/8789158?s=400&v=4
show_downloads: false
google_analytics: UA-143711627-1
email: seungjun.nah@gmail.com