theme: jekyll-theme-minimal
title: Seungjun Nah
description: <p><b>Senior Research Scientist </b><br>NVIDIA</p>
logo: https://avatars1.githubusercontent.com/u/8789158?v=4
show_downloads: false
google_analytics: UA-143711627-1
email: seungjun.nah@gmail.com