# theme: jekyll-theme-cayman
# title: Seungjun Nah's homepage.
# description: Computer Vision Research Blog


# site settings
title: Seungjun Nah
# subtitle: Research Blog
email: seungjun.nah@gmail.com
# description: My research projects will be posted
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "seungjunnah.github.io" # the base hostname & protocol for your site
# author:
# street_address: GwanakRo 1 Seoul National University
# city: Seoul
# state: TN
# zip_code: 08826
# country: Korea, Republic of

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
# 500px_url:
# facebook_url:
github_url: https://github.com/SeungjunNah
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
